version: '3.9'

networks:
  my_inception:

volumes:
  my_db:
    driver_opts:
     type: none
     o: bind
     device: /home/imittous/data/my_db
  wp_files:
    driver_opts:
      type: none
      o: bind
      device: /home/imittous/data/wp_files


services:
  mariadb:
    build: ./srcs/requirements/mariadb
    container_name: mariadb
    image: mariadb
    restart: on-failure
    volumes:
      - my_db:/var/lib/mysql
    networks:
      - my_inception
    env_file:
      - .env
  nginx:
    build: ./srcs/requirements/nginx
    container_name: nginx
    image: nginx
    restart: on-failure
    ports:
      - 443:443
    volumes:
      - wp_files:/var/www/html/wordpress
    networks:
      - my_inception
    depends_on:
      - wordpress
    env_file:
      - .env
  wordpress:
    build: ./srcs/requirements/wordpress
    container_name: wordpress
    image: wordpress
    restart: on-failure
    volumes:
      - wp_files:/var/www/html/wordpress
    networks:
      - my_inception
    depends_on:
      - mariadb
    env_file:
      - .env
  adminer:
    build: ./srcs/requirements/bonus/adminer
    container_name: adminer
    image: adminer
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - my_inception
    volumes:
      - my_db:/var/lib/mysql
  static_website:
    build: ./srcs/requirements/bonus/static_website
    container_name: static_website
    image: static_website
    restart: on-failure
    ports:
      - 1337:80
    networks:
      - my_inception
